platform :ios, '8.0'

target 'reactNativeCompent' do
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/', :subspecs => [
    'DevSupport',
    'Core',
	'ART',
	'RCTActionSheet',
	'RCTGeolocation',
	'RCTImage',
	'RCTNetwork',
	'RCTPushNotification',
	'RCTSettings',
	'RCTText',
	'RCTVibration',
	'RCTWebSocket',
	'RCTLinkingIOS',
  ]
  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/lib/ios/'
  pod 'JPushRN', :path => '../node_modules/jpush-react-native'
  pod 'JCoreRN', :path => '../node_modules/jcore-react-native'
end
